# Generated by Django 5.2.1 on 2025-05-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name_plural': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': 'Footer'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='galleryimages',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='heropage',
            options={'verbose_name_plural': 'Hero Page'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name_plural': 'Logo'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='socialicons',
            options={'verbose_name_plural': 'Social Icons'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials'},
        ),
    ]
